# Generated by Django 4.0.4 on 2022-07-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('ctc', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
