# Generated by Django 4.0.4 on 2022-07-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_viewer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
